version: '3.9'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: akilli-fiyat
      MYSQL_USER: test_kullanici
      MYSQL_PASSWORD: 1234
    ports:
      - "3355:3355"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build: .
    restart: always
    environment:
      DB_URL: jdbc:mysql://mysql:3355/akilli-fiyat?useSSL=false
      DB_USERNAME: test_kullanici
      DB_PASSWORD: 1234
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: