

version: "3.8"

services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: akilli-fiyat
      MYSQL_USER: test_kullanici
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 456321













